import Head from "next/head";
import { useRouter } from "next/router";
import SEO from "../components/SEO";

export default function TermsOfService() {
    const router = useRouter();

    return (
        <>
        <SEO title="Terms of Service" description="Read the Static Engine Terms of Service. By using our platform, you agree to these terms." canonicalUrl="https://staticengine.com/terms" />
        <div style={{ backgroundColor: "#0f172a", minHeight: "100vh", color: "#f8fafc", padding: "40px 20px" }}>
            <Head>
                <title>Terms of Service | Static Engine</title>
            </Head>
            <div style={{ maxWidth: 800, margin: "0 auto", backgroundColor: "#1e293b", padding: "40px", borderRadius: "16px", border: "1px solid #334155" }}>
                <h1 style={{ fontSize: "2.5rem", marginBottom: "8px", fontWeight: "bold" }}>Static Engine<br />Terms of Service</h1>
                <p style={{ color: "#94a3b8", marginBottom: "4px", fontSize: "1rem" }}><strong>Effective Date:</strong> March 6, 2026</p>
                <p style={{ color: "#94a3b8", marginBottom: "32px", fontSize: "1rem" }}><strong>Operated by:</strong> Korsica Brands LLC, Los Angeles, California</p>

                <div style={{ lineHeight: "1.6", color: "#cbd5e1" }}>
                    <p style={{ marginBottom: "24px" }}>
                        Please read these Terms of Service ("Terms") carefully before using Static Engine ("Service"), operated by Korsica Brands LLC ("Company," "we," "us," or "our"). By creating an account, checking the agreement box at signup, or otherwise accessing or using the Service, you agree to be bound by these Terms. If you do not agree, do not use the Service.
                    </p>

                    <h2 style={{ color: "#f8fafc", marginTop: "32px", marginBottom: "12px", fontSize: "1.5rem" }}>1. The Service</h2>
                    <p style={{ marginBottom: "16px" }}>
                        Static Engine is a software-as-a-service platform that uses artificial intelligence to assist users in generating Facebook ad creative, landing pages, and related marketing materials. The Service may integrate with third-party platforms including but not limited to Meta (Facebook), Shopify, and image generation APIs.
                    </p>
                    <p style={{ marginBottom: "16px" }}>
                        We reserve the right to modify, suspend, or discontinue any aspect of the Service at any time with or without notice.
                    </p>

                    <h2 style={{ color: "#f8fafc", marginTop: "32px", marginBottom: "12px", fontSize: "1.5rem" }}>2. Eligibility</h2>
                    <p style={{ marginBottom: "16px" }}>
                        You must be at least 18 years old and capable of forming a binding contract to use the Service. By using the Service, you represent that you meet these requirements. The Service is intended for business use. You represent that you are using the Service on behalf of a business entity or as a professional, not as a consumer.
                    </p>

                    <h2 style={{ color: "#f8fafc", marginTop: "32px", marginBottom: "12px", fontSize: "1.5rem" }}>3. Account Registration</h2>
                    <p style={{ marginBottom: "16px" }}>To access the Service, you must create an account. You agree to:</p>
                    <ul style={{ marginBottom: "16px", paddingLeft: "24px" }}>
                        <li style={{ marginBottom: "8px" }}>Provide accurate and complete information at signup and keep it up to date</li>
                        <li style={{ marginBottom: "8px" }}>Maintain the security of your account credentials</li>
                        <li style={{ marginBottom: "8px" }}>Notify us immediately of any unauthorized access to your account</li>
                        <li style={{ marginBottom: "8px" }}>Accept responsibility for all activity that occurs under your account</li>
                    </ul>
                    <p style={{ marginBottom: "16px" }}>
                        We reserve the right to suspend or terminate accounts that contain inaccurate information or that we reasonably believe have been compromised.
                    </p>

                    <h2 style={{ color: "#f8fafc", marginTop: "32px", marginBottom: "12px", fontSize: "1.5rem" }}>4. AI-Generated Output — Important Disclaimer</h2>

                    <h3 style={{ color: "#f8fafc", marginTop: "24px", marginBottom: "12px", fontSize: "1.25rem" }}>4.1 Nature of AI Output</h3>
                    <p style={{ marginBottom: "16px" }}>The Service uses artificial intelligence to generate marketing copy, ad creative, landing page content, images, and other materials. You acknowledge and agree that:</p>
                    <ul style={{ marginBottom: "16px", paddingLeft: "24px" }}>
                        <li style={{ marginBottom: "8px" }}>All output generated by the Service is AI-generated and may contain errors, inaccuracies, or content that is not suitable for your specific use case</li>
                        <li style={{ marginBottom: "8px" }}>The Company does not guarantee the accuracy, completeness, legality, or fitness for any particular purpose of any AI-generated output</li>
                        <li style={{ marginBottom: "8px" }}>AI-generated output is a starting point and a creative tool, not a finished, verified, or legally reviewed deliverable</li>
                    </ul>

                    <h3 style={{ color: "#f8fafc", marginTop: "24px", marginBottom: "12px", fontSize: "1.25rem" }}>4.2 Your Responsibility to Review</h3>
                    <p style={{ marginBottom: "16px" }}>You are solely responsible for reviewing all AI-generated output before publishing, submitting, or distributing it in any form. This includes but is not limited to:</p>
                    <ul style={{ marginBottom: "16px", paddingLeft: "24px" }}>
                        <li style={{ marginBottom: "8px" }}>Verifying that all claims made in ad copy, landing pages, or other generated content are accurate and substantiated</li>
                        <li style={{ marginBottom: "8px" }}>Ensuring that generated content complies with applicable advertising standards, platform policies (including Meta Advertising Policies), and laws including FTC guidelines on advertising</li>
                        <li style={{ marginBottom: "8px" }}>Confirming that generated content does not infringe on third-party intellectual property rights</li>
                        <li style={{ marginBottom: "8px" }}>Ensuring that product claims, health claims, or any regulated claims comply with applicable regulations</li>
                    </ul>
                    <p style={{ marginBottom: "16px" }}>
                        The Company shall not be liable for any loss, damage, fine, penalty, or other consequence arising from your use or publication of AI-generated output without adequate review.
                    </p>

                    <h3 style={{ color: "#f8fafc", marginTop: "24px", marginBottom: "12px", fontSize: "1.25rem" }}>4.3 No Professional Advice</h3>
                    <p style={{ marginBottom: "16px" }}>
                        Nothing generated by the Service constitutes legal advice, financial advice, medical advice, or any other form of professional advice. Do not rely on Service output as a substitute for qualified professional guidance.
                    </p>

                    <h2 style={{ color: "#f8fafc", marginTop: "32px", marginBottom: "12px", fontSize: "1.5rem" }}>5. Shopify Integration</h2>
                    <p style={{ marginBottom: "16px" }}>
                        The Service offers optional integration with Shopify stores via the Shopify API. By connecting your Shopify store, you authorize the Company to access your store data and push content to your store as necessary to deliver the Service.
                    </p>
                    <p style={{ marginBottom: "16px" }}>You acknowledge and agree that:</p>
                    <ul style={{ marginBottom: "16px", paddingLeft: "24px" }}>
                        <li style={{ marginBottom: "8px" }}>You are solely responsible for your Shopify store and any content published to it, including content generated and pushed by the Service</li>
                        <li style={{ marginBottom: "8px" }}>The Company is not responsible for any disruption, change, error, data loss, or other issue affecting your Shopify store arising from your use of the Service, including any integration or API interaction</li>
                        <li style={{ marginBottom: "8px" }}>The Company will only add new page templates and section files to your store and will not modify or delete any existing theme files. However, you use this integration at your own risk and should maintain backups of your Shopify theme</li>
                        <li style={{ marginBottom: "8px" }}>You must ensure you have the right to authorize the permissions requested during the Shopify OAuth connection process</li>
                        <li style={{ marginBottom: "8px" }}>Disconnecting your store or revoking API access is your responsibility and can be done at any time through your Shopify admin settings</li>
                    </ul>

                    <h2 style={{ color: "#f8fafc", marginTop: "32px", marginBottom: "12px", fontSize: "1.5rem" }}>6. Subscription, Billing & Cancellation</h2>

                    <h3 style={{ color: "#f8fafc", marginTop: "24px", marginBottom: "12px", fontSize: "1.25rem" }}>6.1 Subscription Plans</h3>
                    <p style={{ marginBottom: "16px" }}>
                        The Service is offered on a subscription basis. Pricing, features, and credit allocations for each plan are described on our pricing page and may be updated from time to time. By subscribing, you agree to pay all applicable fees for your selected plan.
                    </p>

                    <h3 style={{ color: "#f8fafc", marginTop: "24px", marginBottom: "12px", fontSize: "1.25rem" }}>6.2 Auto-Renewal</h3>
                    <p style={{ marginBottom: "16px" }}>
                        Subscriptions automatically renew at the end of each billing cycle (monthly or annually, depending on your selected plan) at the then-current rate unless you cancel before the renewal date. By subscribing, you authorize us to charge your payment method on a recurring basis.
                    </p>

                    <h3 style={{ color: "#f8fafc", marginTop: "24px", marginBottom: "12px", fontSize: "1.25rem" }}>6.3 Credits</h3>
                    <p style={{ marginBottom: "16px" }}>
                        Certain features, including the Landing Page Generator, operate on a credit system. Credits are allocated per billing cycle according to your plan tier. Unused credits do not roll over to the next billing cycle unless explicitly stated in your plan description. Additional credits may be purchased at the rates listed on our pricing page.
                    </p>

                    <h3 style={{ color: "#f8fafc", marginTop: "24px", marginBottom: "12px", fontSize: "1.25rem" }}>6.4 Cancellation</h3>
                    <p style={{ marginBottom: "16px" }}>
                        You may cancel your subscription at any time through your account settings. Cancellation takes effect at the end of your current billing cycle. You will retain access to the Service until the end of the period you have paid for. We do not prorate or refund partial billing periods upon cancellation.
                    </p>

                    <h3 style={{ color: "#f8fafc", marginTop: "24px", marginBottom: "12px", fontSize: "1.25rem" }}>6.5 Refunds</h3>
                    <p style={{ marginBottom: "16px" }}>
                        All fees are non-refundable except where required by applicable law. We do not offer refunds for unused credits, partial billing periods, or dissatisfaction with AI-generated output. If you believe you were charged in error, contact us at the email address listed in Section 12 within 30 days of the charge.
                    </p>

                    <h2 style={{ color: "#f8fafc", marginTop: "32px", marginBottom: "12px", fontSize: "1.5rem" }}>7. Acceptable Use</h2>
                    <p style={{ marginBottom: "16px" }}>You agree not to use the Service to:</p>
                    <ul style={{ marginBottom: "16px", paddingLeft: "24px" }}>
                        <li style={{ marginBottom: "8px" }}>Generate content that is false, misleading, deceptive, or fraudulent</li>
                        <li style={{ marginBottom: "8px" }}>Violate any applicable law, regulation, or third-party platform policy, including Meta Advertising Policies</li>
                        <li style={{ marginBottom: "8px" }}>Infringe on any third-party intellectual property, privacy, or other rights</li>
                        <li style={{ marginBottom: "8px" }}>Generate content that is defamatory, obscene, harassing, or otherwise objectionable</li>
                        <li style={{ marginBottom: "8px" }}>Attempt to reverse engineer, decompile, or extract the underlying AI models or prompts used by the Service</li>
                        <li style={{ marginBottom: "8px" }}>Resell, sublicense, or otherwise transfer access to the Service to third parties without our express written consent</li>
                        <li style={{ marginBottom: "8px" }}>Use the Service in any way that could damage, disable, or impair our infrastructure or interfere with other users</li>
                    </ul>
                    <p style={{ marginBottom: "16px" }}>
                        We reserve the right to suspend or terminate your account for any violation of this section without prior notice and without refund.
                    </p>

                    <h2 style={{ color: "#f8fafc", marginTop: "32px", marginBottom: "12px", fontSize: "1.5rem" }}>8. Intellectual Property</h2>

                    <h3 style={{ color: "#f8fafc", marginTop: "24px", marginBottom: "12px", fontSize: "1.25rem" }}>8.1 Your Content</h3>
                    <p style={{ marginBottom: "16px" }}>
                        You retain ownership of any content you input into the Service, including product information, images, and descriptions. By using the Service, you grant the Company a limited, non-exclusive license to use your input content solely to deliver the Service to you.
                    </p>

                    <h3 style={{ color: "#f8fafc", marginTop: "24px", marginBottom: "12px", fontSize: "1.25rem" }}>8.2 Generated Output</h3>
                    <p style={{ marginBottom: "16px" }}>
                        Subject to your compliance with these Terms and payment of applicable fees, the Company assigns to you any rights it may hold in the AI-generated output produced specifically for you through the Service. You are responsible for ensuring that the output does not infringe third-party rights before use.
                    </p>
                    <p style={{ marginBottom: "16px" }}>
                        The Company retains ownership of the Service itself, including all templates, software, systems, prompt engineering, and underlying technology. Nothing in these Terms grants you any rights in the Service or the Company's proprietary technology.
                    </p>

                    <h2 style={{ color: "#f8fafc", marginTop: "32px", marginBottom: "12px", fontSize: "1.5rem" }}>9. Disclaimer of Warranties</h2>
                    <p style={{ marginBottom: "16px", textTransform: "uppercase" }}>
                        THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMITTED BY LAW, THE COMPANY EXPRESSLY DISCLAIMS ALL WARRANTIES, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, AND NON-INFRINGEMENT.
                    </p>
                    <p style={{ marginBottom: "16px" }}>
                        We do not warrant that the Service will be uninterrupted, error-free, or free of viruses or other harmful components. We do not warrant that any AI-generated output will be accurate, complete, suitable for your intended use, or compliant with any applicable law or platform policy.
                    </p>

                    <h2 style={{ color: "#f8fafc", marginTop: "32px", marginBottom: "12px", fontSize: "1.5rem" }}>10. Limitation of Liability</h2>
                    <p style={{ marginBottom: "16px", textTransform: "uppercase" }}>
                        TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL KORSICA BRANDS LLC, ITS OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS, LOSS OF DATA, BUSINESS INTERRUPTION, OR LOSS OF GOODWILL, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF OR INABILITY TO USE THE SERVICE, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
                    </p>
                    <p style={{ marginBottom: "16px", textTransform: "uppercase" }}>
                        OUR TOTAL CUMULATIVE LIABILITY TO YOU FOR ANY CLAIMS ARISING OUT OF OR RELATED TO THESE TERMS OR THE SERVICE SHALL NOT EXCEED THE GREATER OF (A) THE TOTAL FEES PAID BY YOU TO THE COMPANY IN THE THREE MONTHS PRECEDING THE CLAIM OR (B) ONE HUNDRED U.S. DOLLARS ($100).
                    </p>

                    <h2 style={{ color: "#f8fafc", marginTop: "32px", marginBottom: "12px", fontSize: "1.5rem" }}>11. Indemnification</h2>
                    <p style={{ marginBottom: "16px" }}>
                        You agree to indemnify, defend, and hold harmless Korsica Brands LLC and its officers, directors, employees, and agents from and against any claims, liabilities, damages, losses, fines, penalties, and expenses (including reasonable attorneys' fees) arising out of or related to:
                    </p>
                    <ul style={{ marginBottom: "16px", paddingLeft: "24px" }}>
                        <li style={{ marginBottom: "8px" }}>Your use of the Service or any output generated by the Service</li>
                        <li style={{ marginBottom: "8px" }}>Your violation of these Terms</li>
                        <li style={{ marginBottom: "8px" }}>Your violation of any applicable law, regulation, or third-party platform policy</li>
                        <li style={{ marginBottom: "8px" }}>Any content you publish using materials generated by the Service</li>
                        <li style={{ marginBottom: "8px" }}>Your Shopify store or any other third-party platform you connect to the Service</li>
                    </ul>

                    <h2 style={{ color: "#f8fafc", marginTop: "32px", marginBottom: "12px", fontSize: "1.5rem" }}>12. Governing Law & Dispute Resolution</h2>
                    <p style={{ marginBottom: "16px" }}>
                        These Terms shall be governed by and construed in accordance with the laws of the State of California, without regard to its conflict of law provisions. Any dispute arising out of or related to these Terms or the Service shall be resolved by binding arbitration in Los Angeles County, California, under the rules of the American Arbitration Association, except that either party may seek injunctive relief in a court of competent jurisdiction.
                    </p>
                    <p style={{ marginBottom: "16px" }}>
                        You waive any right to participate in a class action lawsuit or class-wide arbitration against the Company.
                    </p>

                    <h2 style={{ color: "#f8fafc", marginTop: "32px", marginBottom: "12px", fontSize: "1.5rem" }}>13. Changes to These Terms</h2>
                    <p style={{ marginBottom: "16px" }}>
                        We reserve the right to update or modify these Terms at any time. We will notify you of material changes by email or by posting a notice within the Service. Your continued use of the Service after the effective date of any changes constitutes your acceptance of the updated Terms. If you do not agree to the updated Terms, you must stop using the Service and cancel your subscription.
                    </p>

                    <h2 style={{ color: "#f8fafc", marginTop: "32px", marginBottom: "12px", fontSize: "1.5rem" }}>14. Termination</h2>
                    <p style={{ marginBottom: "16px" }}>
                        We may suspend or terminate your account and access to the Service at any time, with or without cause, and with or without notice. Upon termination, your right to use the Service ceases immediately. Sections 4, 8, 9, 10, 11, and 12 of these Terms survive termination.
                    </p>

                    <h2 style={{ color: "#f8fafc", marginTop: "32px", marginBottom: "12px", fontSize: "1.5rem" }}>15. Contact</h2>
                    <p style={{ marginBottom: "16px" }}>If you have questions about these Terms or the Service, please contact us at:</p>
                    <p style={{ marginBottom: "16px" }}>
                        <strong>Korsica Brands LLC</strong><br />
                        Los Angeles, California<br />
                        Email: <a href="mailto:contact@staticengine.com" style={{ color: "#3ECFCF", textDecoration: "none" }}>contact@staticengine.com</a>
                    </p>

                    <div style={{ marginTop: "32px", padding: "16px", backgroundColor: "rgba(239, 68, 68, 0.1)", border: "1px solid #ef4444", borderRadius: "8px" }}>
                        <p style={{ margin: 0, fontSize: "0.9rem", color: "#fca5a5" }}>
                            <strong>Note:</strong> These Terms of Service have been prepared as a starting-point template. You should have a qualified attorney review and finalize this document before publishing it on your website.
                        </p>
                    </div>
                </div>

                <div style={{ marginTop: "40px", paddingTop: "20px", borderTop: "1px solid #334155", textAlign: "center" }}>
                    <button
                        onClick={() => { router.back(); }}
                        style={{ background: "none", border: "none", color: "#3ECFCF", fontWeight: "bold", fontSize: "1rem", cursor: "pointer" }}
                    >
                        &larr; Back to App
                    </button>
                </div>
            </div>
        </div>
        </>
    );
}
