import Head from "next/head";

export default function TermsOfService() {
    return (
        <div style={{ backgroundColor: "#0f172a", minHeight: "100vh", color: "#f8fafc", padding: "40px 20px" }}>
            <Head>
                <title>Terms of Service | Static Engine</title>
            </Head>
            <div style={{ maxWidth: 800, margin: "0 auto", backgroundColor: "#1e293b", padding: "40px", borderRadius: "16px", border: "1px solid #334155" }}>
                <h1 style={{ fontSize: "2rem", marginBottom: "8px", fontWeight: "bold" }}>Terms of Service</h1>
                <p style={{ color: "#94a3b8", marginBottom: "32px", fontSize: "0.9rem" }}>Last Updated: March 2026</p>

                <div style={{ lineHeight: "1.6", color: "#cbd5e1" }}>
                    <h2 style={{ color: "#f8fafc", marginTop: "24px", marginBottom: "12px", fontSize: "1.25rem" }}>1. Acceptance of Terms</h2>
                    <p style={{ marginBottom: "16px" }}>By accessing or using Static Engine, you agree to be bound by these Terms of Service. If you do not agree to all the terms and conditions, you must not use our services.</p>

                    <h2 style={{ color: "#f8fafc", marginTop: "24px", marginBottom: "12px", fontSize: "1.25rem" }}>2. Use of AI Services</h2>
                    <p style={{ marginBottom: "16px" }}>Our platform provides AI-driven functionality. You are responsible for any content you generate using our services and must ensure it complies with applicable laws and regulations.</p>

                    <h2 style={{ color: "#f8fafc", marginTop: "24px", marginBottom: "12px", fontSize: "1.25rem" }}>3. User Accounts</h2>
                    <p style={{ marginBottom: "16px" }}>You must provide accurate information when creating an account. You are responsible for maintaining the security of your account credentials.</p>

                    <h2 style={{ color: "#f8fafc", marginTop: "24px", marginBottom: "12px", fontSize: "1.25rem" }}>4. Intellectual Property</h2>
                    <p style={{ marginBottom: "16px" }}>All platform intellectual property belongs to Static Engine. Content generated by you remains your property, subject to our license to operate the service.</p>

                    <h2 style={{ color: "#f8fafc", marginTop: "24px", marginBottom: "12px", fontSize: "1.25rem" }}>5. Termination</h2>
                    <p style={{ marginBottom: "16px" }}>We reserve the right to terminate or suspend access to our service immediately, without prior notice, for conduct that we believe violates these Terms.</p>
                </div>

                <div style={{ marginTop: "40px", paddingTop: "20px", borderTop: "1px solid #334155", textAlign: "center" }}>
                    <a href="/login" style={{ color: "#3ECFCF", textDecoration: "none", fontWeight: "bold" }}>&larr; Back to App</a>
                </div>
            </div>
        </div>
    );
}
